# Generated by Django 2.0.8 on 2018-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendingAlbums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spotifyAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('artist', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('release', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
