# Generated by Django 2.0.8 on 2018-09-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendingAlbums', '0002_spotifyalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyalbum',
            name='album_type',
            field=models.CharField(default='single', max_length=200),
            preserve_default=False,
        ),
    ]
